name: Issue submission form
description: Submit a new rule and fix 
title: "[Rule&Fix]: "
labels: [rule, fix]
assignees:
  - fixerTwo
body:
  - type: markdown
    attributes:
      value: |
        Tahnk you for submitting a new security finding rules & fix to CrowdQ!
  - type: input
    id: contact
    attributes:
      label: Who are you?
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: vuln-details
    attributes:
      label: What vulnerability are you trying to find?
      description: Give us some details about the finding you would like to find and fix.
      placeholder: Give us a short description of the finding you are after!
      value: "Describe the vulnerability to the best of your ability!"
    validations:
      required: true
  - type: textarea
    id: find-rule
    attributes:
      label: How we can find the vulnerable code?
      description: Tell us how we can find this vulnerability and attach a vulnerable code sample.
      placeholder: Rules description and sample bad code. 
      value: "Eg. When using document.write it is dangerous to use a direct user input. " 
    validations:
      required: true
  - type: textarea
    id: fix-rule
    attributes:
      label: How we can fix this vulnerability?
      description: Tell us how this vulnerability can be fixed and attach a code sample that was fixed.
      placeholder: Fix description and sample fixed code. 
      value: "Eg. When using document.write it is dangerous to use a direct user input. Bad code: <script>document.write(<%request.getParameter(\"userid\")%>))</script>"
    validations: 
      required: false
- type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
